version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-cloud-provisioner
    ports:
      - "5060:5060" # Map the container port 5060 to host port 5060
    environment:
      # Example environment variables (replace with actual variables if needed)
      - APP_ENV=production
      - LOG_LEVEL=info
    volumes:
      - .:/app # Mount the project directory for local development (optional)
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432" # Map the container port 5432 to host port 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multicloud
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: