project_name: cloudcrafter
dist: dist

# Define builds for CLI and Server
builds:
  - id: cli
    binary: cloudcrafter-cli
    main: ./cmd/cli/cli.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  - id: server
    binary: cloudcrafter-server
    main: ./cmd/server/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Package binaries into tar.gz archives
archives:
  - id: cli
    name_template: "{{ .ProjectName }}-cli_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - dist/cloudcrafter-cli
  - id: server
    name_template: "{{ .ProjectName }}-server_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - dist/cloudcrafter-server

# GitHub release settings
release:
  github:
    owner: your-github-username
    name: cloudcrafter

# Generate checksums
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"