# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.13/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "70e08a418ab84d504087a763ebcfebde7ceca760f3fd19543b2f7852db7138ed"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.13/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "866a2ae05fe9c6e402563946ee63dcfd64b636482121e864b41ad5349d1d9f6f"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.13/cloudcrafter-linux-amd64.tar.gz"
        sha256 "bc0fe4157e2f0feae777793dbf4e2009641c92c82ac28159ff43821a01f7268b"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.13/cloudcrafter-linux-arm64.tar.gz"
        sha256 "ac5e1015e23d15f2f9aded5516ea13a00030c1e39acff8681f768ce4f13b8cbf"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
