name: Release Automation

on:
  push:
    tags:
      - 'v*' # Trigger when tags are manually pushed
  workflow_run:
    workflows:
      - Auto Tagging # Name of the tagging workflow
    types:
      - completed

permissions:
  contents: write

jobs:
  tag-build-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build Go Binary
        run: |
          echo "Building Go binary..."
          go build -o cloudcrafter ./cmd/cli
          ls -l cloudcrafter # Ensure the binary exists 
      
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}