name: Release Automation

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows:
      - Auto Tagging
    types:
      - completed

permissions:
  contents: write

jobs:
  tag-build-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-cache-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-v1-

      - name: Build Go Binary
        run: |
          echo "Building Go binary..."
          go build -o cloudcrafter ./cmd/cli
          ls -l cloudcrafter

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
