name: Auto Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  auto-tag:
    name: Auto Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Determine Next Version
        id: version
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          major=$(echo $latest | cut -d. -f1 | tr -d 'v')
          minor=$(echo $latest | cut -d. -f2)
          patch=$(echo $latest | cut -d. -f3)
          next_version="v$major.$minor.$((patch + 1))"
          echo "next_version=$next_version" >> "$GITHUB_OUTPUT"

      - name: Create and Push Tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.next_version }}
          git push origin ${{ steps.version.outputs.next_version }}